### PR TITLE
HTML Activation Link Mail Template

### PR DESCRIPTION
**Pull request by anne27**
User-friendly template, contains links to Twitter, Facebook, Google+ and Youtube profiles for Yunity.
Image needs review.
Confirmation link not yet integrated with backend.

### CODE REVIEW

**Comment by tiltec** [comment]
First of all, thanks for your great work! This will definitely be useful!

Some remarks:

1. As the template will be used for https://foodsaving.world/, the design could be more similar to the website (e.g. using the logo, brownish colors, Material Design)
2. yunity and foodsaving worldwide are related, but not the same. I think it's unexpected for someone who signs up to see the yunity social links

If that is resolved, we can integrate it with the backend ( #269 ) and the text templates ( #268 ). The directory is ` foodsaving/users/templates/`.

It's very convenient to split the HTML templates into a base part and a content part. An example can be found in the [taiga.io backend code](https://github.com/taigaio/taiga-back/tree/master/taiga/projects/templates/emails). This ensures that all mails have a similar look and feel and reduces duplication.

Feel free to contact me on Slack!

**Comment by anne27** [comment]
Just modified a little to match the formatting in the webapp.

template

**Comment by tiltec** [comment]
I like it very much!

We don't have a privacy statement or terms of service right now, but it would be good to have in future..

I would merge that template later today, what do you think? It still needs splitting into a base template and body (see last comment), but we can do that as soon as the templated mail sending is implemented.

**Comment by anne27** [comment]
@tiltec Sure, you may merge it! I will start working on splitting it soon. :)

**Pull request merged**
