### PR TITLE
Revert "Speed up test execution"

### PR DESCRIPTION
**Pull request by tiltec**
Reverts yunity/foodsaving-backend#338

I did some benchmarks and it doesn't seem worth it. 10% speedup on single process versus slight losses with more processes and keeping the database across test runs.

There's some spurious test failures with the new config when I run 4 parallel processes with keepdb: https://gist.github.com/tiltec/73bd8164597ea5fc1413a7803a3d4c94
But this might be related to other changes. I will do a git bisect to find out more.

Note: it's not surprising to see no significant differences between 3 and 4 processes on my machine as it's a _two-real-core_ CPU with hyperthreading (i5-2520M 2.50GHz)

```
$ time for i in {1..10}; do ./manage.py test; done

# branch speed-up-test

real	1m41.099s
user	1m15.923s
sys	0m3.053s

# old config

real	1m52.395s
user	1m23.067s
sys	0m4.187s

# -> 10 % speedup


$ time for i in {1..10}; do ./manage.py test --parallel 4; done

# branch speed-up-test

real	1m33.021s
user	1m44.060s
sys	0m5.467s

# old config

real	1m29.427s
user	1m50.193s
sys	0m6.340s

# -> 4% slowdown


$ time for i in {1..10}; do ./manage.py test --parallel 3 --keepdb; done

# branch speed-up-test

real	1m0.897s
user	1m34.340s
sys	0m5.027s

# old config

real	0m56.926s
user	1m24.163s
sys	0m5.250s


$ time for i in {1..10}; do ./manage.py test --parallel 4 --keepdb; done

# branch speed-up-test
# throws error like this https://gist.github.com/tiltec/73bd8164597ea5fc1413a7803a3d4c94
# also with 5 or more parallel runners

# EDIT it works now! don't know why

real	0m53.577s
user	1m40.807s
sys	0m4.907s

# old config

real	0m56.047s
user	1m33.710s
sys	0m5.980s
```

### CODE REVIEW

**Comment by nicksellen** [comment]
I get:

### "Fast" (`master` as of now)

```
time for i in {1..10}; do ./manage.py test --parallel 4 --keepdb; done
```

```
real	0m53.510s
user	1m56.030s
sys	0m6.780s
```

### "Slow" (`revert-338-speed-up-tests` as of now)

```
time for i in {1..10}; do ./manage.py test --parallel 4 --keepdb; done
```

```
real	1m13.171s
user	2m37.157s
sys	0m10.123s
```

It shaves 20s off the time (27%) = worth it ;)

If it makes them run differently/incorrectly thats another question though... is it true?

**Comment by nicksellen** [comment]
Copying my comment from [your gist](https://gist.github.com/tiltec/73bd8164597ea5fc1413a7803a3d4c94):

> django.db.utils.ProgrammingError: column conversations_conversation.target_type_id does not exist

I had some of these before, but I think it was due to using --keepdb with a database with old/incorrect schema.

**Comment by tiltec** [comment]
Seems like you have another bottleneck though... I would expect X250 to be generally faster (or at least same speed) as X220

**Comment by tiltec** [comment]
I didn't do anything to optimize my machine for speed btw.. Firefox with a lot of tabs open, Slack app, Pycharm

**Comment by nicksellen** [comment]
> Seems like you have another bottleneck though... I would expect X250 to be generally faster (or at least same speed) as X220

Sure, but right now, that's the results I get, I don't really mind what master has, but I'm gunna have me these test settings :)

**Comment by tiltec** [comment]
I ran it on circleci via ssh with those results:

## single process

```
$ time for i in {1..10}; do ./manage.py test --keepdb; done
```

### "slow" (this branch)

```
real	1m35.989s
user	1m13.902s
sys	0m4.774s
```

### "fast" (`master`)

```
real	1m37.880s
user	1m15.095s
sys	0m4.972s
```

## 2 processes

```
$ time for i in {1..10}; do ./manage.py test --parallel 2 --keepdb; done
```

### "slow" (this branch)

```
real	1m20.850s
user	1m51.079s
sys	0m6.434s
```

### "fast" (`master`)

```
real	1m21.860s
user	1m47.914s
sys	0m5.637s
```

## 4 processes

```
$ time for i in {1..10}; do ./manage.py test --parallel 4 --keepdb; done
```

### "slow" (this branch)

```
real	1m24.215s
user	1m55.257s
sys	0m6.992s
```

### "fast" (`master`)

```
real	1m20.217s
user	1m50.175s
sys	0m5.800s
```

I don't see consistent speed-up.

@nicksellen are you interested to investigate this further? Do you want to keep the changes?

If yes I would suggest to keep the settings file in the repo, but undo the changes in `./manage.py`. You could explicitly enable it via the `settings` parameter of django-admin:

```
./manage.py test --settings=config.test_settings
```
(from https://stackoverflow.com/questions/4909958/django-local-settings/14545196#14545196)

You could add this to your bash alias.

**Comment by nicksellen** [comment]
> If yes I would suggest to keep the settings file in the repo, but undo the changes in ./manage.py. You could explicitly enable it via the settings parameter of django-admin

yes, lets go for that before I use up all the time I saved from the faster tests :p

**Pull request merged**
